### ISSUE TITLE
Error when deleting integer from list creation

### ISSUE THREAD

**Issue by jtweeder** [jtweeder/mealcurator#47]
Error occurs when a users deletes the integer default of 0 and puts in a fractional measurement only.

TODO:  Check for null/non-entry and default to zero if a fractional measurement was provided.

**Comment by akshatmishra1203** [comment]
Hey I want to contribute.
Can I contribute 
Please assign me.

**Comment by jtweeder** [comment]
Hey, @akshatmishra1203 , thanks for the interest.  Currently, have PR #48  pending a fix from @itsmohamedyahia that would resolve this.

Stay tuned though....will have plenty more good first issues things crop up in the future I am sure.
